# Generated by Django 5.2.5 on 2025-08-30 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Secondary', 'Secondary'), ('Higher Secondary', 'Higher Secondary'), ('Graduation', 'Graduation'), ('Diploma', 'Diploma'), ('M.Phil', 'M.Phil'), ('Ph.D.', 'Ph.D.'), ('Other', 'Other')], max_length=100)),
                ('institution_name', models.CharField(max_length=255)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('subjects_specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('subjects_taught', models.CharField(blank=True, max_length=255, null=True)),
                ('classes_taught', models.CharField(blank=True, max_length=255, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('total_years_experience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(blank=True, max_length=255, null=True)),
                ('classes_sections_taught', models.CharField(blank=True, max_length=255, null=True)),
                ('subjects_taught', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_responsibilities', models.TextField(blank=True, null=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='teachers.teacher')),
            ],
        ),
    ]
