# Generated by Django 5.2.5 on 2025-08-30 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
                ('teachers', models.ManyToManyField(blank=True, to='teachers.teacher')),
                ('subjects', models.ManyToManyField(to='classes.subject')),
            ],
        ),
    ]
